### ISSUE TITLE
Can't start container since last commit

### ISSUE THREAD

**Issue by lokiiiii** [xataz/gobrowser#12]
Hello Xataz =)
Depuis le dernier commit, lorsque j'essaye de démarrer mon container depuis mon docker-compose, j'ai les erreurs suivantes:

ERROR: for 242430134a55_gobrowser  Cannot start service gobrowser: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"./app\": permission denied": unknown

ERROR: for gobrowser  Cannot start service gobrowser: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"./app\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by xataz** [comment]
C'est vrai que j'ai fait pas mal de changement, l'image était vieille et non sécurisé (lancement en root entre autre).

En fait maintenant y'a plus besoin de command, tout est géré par les variables d'environnement.

Peux tu me fournir ta commande ou la partie de ton docker-compose pour que je te montre la nouvelle méthode.

Je vais rajouter tout ça dans le README

**Comment by lokiiiii** [comment]
Hello :)

Voici mon docker-compose pour la partie gobrowser:

  gobrowser:
    image: xataz/gobrowser
    container_name: gobrowser
    environment:
      - APP_UID=1000
      - APP_GID=1000
    volumes:
      - /data:/home
      - /docker/data/gobrowser/share:/share
    command: ./app -listen 0.0.0.0:0000 -webroot /exemple -forcessl true -Forceurl exemple.fr
    restart: always

Du coup, j'ai juste à supprimer la ligne "commande" ?
Il faudrait que je rajoute les env pour les paramètres ?

Merci encore ;)

**Comment by xataz** [comment]
Yes voilà, ce qui donnerai :
```yaml
gobrowser:
  image: xataz/gobrowser
  container_name: gobrowser
  environment:
    - UID=1000
    - GID=1000
    - WEBROOT=/xo
    - FORCE_SSL=true
    - FORCE_URL=xxxxx.fr
  volumes:
    - /data:/home
    - /docker/data/gobrowser/share:/share
  restart: always
```
